travis:
  secure:
    BINSTAR_TOKEN: KnCKHRmTf3n9C8KmaoZZAxklN1vtYCLB+sLeHClCJWYScNKmjSg/gMaMCumTnrPf4EYzFDqr7+hRlFz3AYjmhkNgUeV4QSKhulPW4NxCpjYgYlQ/edi8voRqNLGjy4dTKfa2+x8QfnH9O5gbt9dUqewBa/ZWOwiFood/FBgfBTXwHGuV0yx3I+q+VV+WwvG8bRRzvHIbFJgMBvMx2A9ZXr8T61mr+/3+EJT062/eor/UzQRGXnzJrLR705LHaDOShEd1BttcCoaHGz+Uyp7Idv/tvzFVJykN6gZSKGJujMC65a3FwmuKcPw2rmxpo83okCj9ZSi7LoxTLgl82jcvurPmMxkXMzivtTZpAQufpBFMq66FkzHt6YiGLKZbVd8A8DhTpoBdne9SHB4nzJAJeTiswpeRLn5rDaAvsu2puaK3Iz7w8eyOVS5eyioK1W/ZbbQmlZLk5nmQEFtRAgvSBH+BZZgbKm7FYgrqTZPopitlC7VIWw/aXwSrCbs6kXvXB2Mu7LTV0+RVg06HFrH6EyUUGvJXcJFkyu32sD9q3aGC1WZ9GYjmv8sdV5ahDG+IwUlIPAi2Az3Jsf/svN1A5d00FBO/jp1BFcR6mrVzIa36e9717DUaOTu5A6NLJBYnMW8SksyVsYklJy9YhXv55DLL+xm/lIEKKiGPpbpCcTc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
